version: '3.2'

services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    ports:
      - '80:80'
    networks:
      - app-network
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=my_password_root
      - MYSQL_DATABASE=ms_asana
      - MYSQL_USER=igor
      - MYSQL_PASSWORD=memory85
    ports:
      - '3311:3306'
    volumes:
      - "./docker/mysql:/var/lib/mysql"
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - '8888:80'
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
    depends_on:
      - db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
